config/routes.rb
Rails.application.routes.draw do
  
  get 'auth/:provider/callback', to: 'sessions#auth_create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :users do
    resources :directions
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  root 'welcome#index'

end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :user
end

app/models/directions_client.rb
require 'httparty'
require 'json'
require 'awesome_print'

class DirectionsClient
  include HTTParty
  base_uri 'https://maps.googleapis.com/maps/api/directions/json'

  def make_api_request(args={})
    origin = args.fetch(:origin)
    destination = args.fetch(:destination)
    mode = args.fetch(:mode)

    response = self.class.get('',
                              query: {
                                key: ENV['GOOGLE_API_KEY'],
                                origin: origin,
                                destination: destination,
                                mode: mode
                              })

    if response.success?
      json = JSON.parse(response.body)
      distance = json["routes"][0]["legs"][0]["distance"]["text"]
      duration = json["routes"][0]["legs"][0]["duration"]["text"]
      return {distance: distance, duration: duration}
    else
      "Duration Request Failed"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :directions
  has_many :identities
	has_secure_password

  validates :email, { presence: true,
                      uniqueness: { case_sensitive: true, message: "Same email exists" },
                      length: { minimum: 3, message: "Email should be longer than 3 characters" },
                      format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/, message: "Must be in Email form"}
                    }

  

  def self.from_omniauth(auth_hash)
    user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
    # needs checker method to check whether same email exists
    user.email = auth_hash['info']['email'] 
    user.password_digest = (0...50).map { ('a'..'z').to_a[rand(26)] }.join
    user.image = auth_hash['info']['image']
    user.save!
    return user
  end    
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    # session.clear
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  # if @current_user.nil?
  #   @current_user = User.find(session[:user_id])
  # end

  def signed_in
  	!!current_user
  end
  helper_method :check_signed_in


end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @directions = @user.directions
    @props = {
      directions: @user.directions.last(5),
      url: user_directions_path(@user),
      request_forgery_token: request_forgery_protection_token,
      form_authenticity_token: form_authenticity_token
    }

    respond_to do |format|
      format.html {render :index}
      format.json {render json: @props}
    end

  end


  def show
    @direction = Direction.find(params[:id])
  end


  def new
    @direction = Direction.new
  end


  def edit
  end


  def create
    @user = User.find(params[:user_id])

    @direction = @user.directions.new(
      origin: params[:origin],
      destination: params[:destination],
      mode: params[:mode]
    )

    direction_client = DirectionsClient.new

    response = direction_client.make_api_request(
      origin: params[:origin],
      destination: params[:destination],
      mode: params[:mode])

    @direction.duration = response[:duration]
    @direction.distance = response[:distance]

    if @direction.save
      respond_to do |format| 
        format.html {render :show}
        format.json {render json: @user.directions.last(5)}
      end
    else 
      render :new
    end 

  end



  def update
  end


  def destroy
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end


  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to '/login'
    end
  end


  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

  
  def auth_create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to user_path(user)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end


  def new
    @user = User.new
  end


  def edit
    @user = User.find(params[:id])
  end


  def create
    @user = User.new(user_params)

    if @user.save
    	session[:user_id] = @user.id
      flash[:notice] = "Thank you for signing up"
    	redirect_to @user
    else
      flash[:notice] = "Unable to signup"
    	redirect_to '/signup'
    end
  end


  def update
  end


  def destroy
    @user.destroy
  end


  private
    def user_params
      params.require(:user).permit(:email, :password)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/directions/_form.html.erb
<%= form_for(@direction), url: user_directions_path do |f| %>
  <% if @direction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@direction.errors.count, "error") %> prohibited this direction from being saved:</h2>

      <ul>
      <% @direction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directions/_map.html.erb
<div id='map'></div>

app/views/directions/index.html.erb
<%= react_component :DirectionBox, @props %>

app/views/directions/new.html.erb
<h1>New Direction</h1>

<%= form_for :direction, url: user_directions_path do |f| %>

  <% if @direction.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@direction.errors.count, "error") %> prohibited
        this direction from being saved:
      </h2>
      <ul>
        <% @direction.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </p>

  <p>
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </p>


  <p>
    <%= f.label :mode %><br>
    <%= f.text_field :mode %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>


<%= link_to 'Back to Directions', user_directions_path %>

app/views/directions/show.html.erb
<h1>This is Direction #<%= @direction.id %></h1><br>

<h3>
	From:<div id='dir-origin'><%= @direction.origin %></div>
	To:<div id='dir-destination'><%= @direction.destination %></div>
	By:<div id='dir-mode'><%= @direction.mode %></div>
	<div id='dir-distance'>Distance: <%= @direction.distance %></div>
	<div id='dir-duration'>Duration: <%= @direction.duration %></div>
</h3>


<%= link_to 'Back to Directions', user_directions_path %>
<%= render 'map' %>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMapProject</title>

	<script src="http://maps.googleapis.com/maps/api/js?key=#{GOOGLE_API_KEY}"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= react_component :WelcomeGofast %>

	<% if current_user %>
		Signed in as <strong><%= current_user.email %></strong>
		<%= link_to "Sign out", signout_path, id: "sign_out" %>
	<% else %>
		<div><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %></div>
		<div><%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %></div>
	<% end %>

	<%= yield %>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Hello~</h1><br>

<div><img src= "<%= @user.image %>" ></div>
<div><%= @user.email %></div><br>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Directions', user_directions_path(@user) %> 

app/views/welcome/index.html.erb
<%= link_to 'Sign up', new_user_path %>
<%= link_to 'Sign in', '/login' if current_user.nil? %>
<%= link_to 'My Directions', user_directions_path(current_user) if current_user %>